version: '3'

services:

  db:
    build: ./db
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: challenge3
      # MARIADB_USER: challenge3
      # MARIADB_PASSWORD: challenge3

  api:
    build: ./api
    environment:
      - PORT=8080 
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_DATABASE=challenge3

    depends_on:
      - db
    deploy:
      replicas: 3

  nginx:
    build: ./nginx
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
